version: '3.6'

services:
  db:
    image: postgres:16.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build: .
    container_name: shopgo_api
    ports:
      - "8001:8001"
    env_file:
      - .env 
    depends_on:
      - db
    networks:
      - backend


volumes:
  db_data:

networks:
  backend:
    driver: bridge
