// Code generated by mockery. DO NOT EDIT.

package repocustom

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// MockUserRoleById is an autogenerated mock type for the UserRoleById type
type MockUserRoleById struct {
	mock.Mock
}

type MockUserRoleById_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRoleById) EXPECT() *MockUserRoleById_Expecter {
	return &MockUserRoleById_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: db, userId
func (_m *MockUserRoleById) Execute(db *gorm.DB, userId uuid.UUID) (string, error) {
	ret := _m.Called(db, userId)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) (string, error)); ok {
		return rf(db, userId)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) string); ok {
		r0 = rf(db, userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uuid.UUID) error); ok {
		r1 = rf(db, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRoleById_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUserRoleById_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - db *gorm.DB
//   - userId uuid.UUID
func (_e *MockUserRoleById_Expecter) Execute(db interface{}, userId interface{}) *MockUserRoleById_Execute_Call {
	return &MockUserRoleById_Execute_Call{Call: _e.mock.On("Execute", db, userId)}
}

func (_c *MockUserRoleById_Execute_Call) Run(run func(db *gorm.DB, userId uuid.UUID)) *MockUserRoleById_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRoleById_Execute_Call) Return(_a0 string, _a1 error) *MockUserRoleById_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRoleById_Execute_Call) RunAndReturn(run func(*gorm.DB, uuid.UUID) (string, error)) *MockUserRoleById_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRoleById creates a new instance of MockUserRoleById. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRoleById(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRoleById {
	mock := &MockUserRoleById{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
