// Code generated by mockery. DO NOT EDIT.

package repogeneric

import (
	entity "github.com/thanyakwaonueng/shopgo/lib/database/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockCategory is an autogenerated mock type for the Category type
type MockCategory struct {
	mock.Mock
}

type MockCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategory) EXPECT() *MockCategory_Expecter {
	return &MockCategory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: tx, category
func (_m *MockCategory) Create(tx *gorm.DB, category *entity.Category) error {
	ret := _m.Called(tx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Category) error); ok {
		r0 = rf(tx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx *gorm.DB
//   - category *entity.Category
func (_e *MockCategory_Expecter) Create(tx interface{}, category interface{}) *MockCategory_Create_Call {
	return &MockCategory_Create_Call{Call: _e.mock.On("Create", tx, category)}
}

func (_c *MockCategory_Create_Call) Run(run func(tx *gorm.DB, category *entity.Category)) *MockCategory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Category))
	})
	return _c
}

func (_c *MockCategory_Create_Call) Return(_a0 error) *MockCategory_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategory_Create_Call) RunAndReturn(run func(*gorm.DB, *entity.Category) error) *MockCategory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: tx, category
func (_m *MockCategory) Delete(tx *gorm.DB, category *entity.Category) error {
	ret := _m.Called(tx, category)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Category) error); ok {
		r0 = rf(tx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategory_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategory_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - tx *gorm.DB
//   - category *entity.Category
func (_e *MockCategory_Expecter) Delete(tx interface{}, category interface{}) *MockCategory_Delete_Call {
	return &MockCategory_Delete_Call{Call: _e.mock.On("Delete", tx, category)}
}

func (_c *MockCategory_Delete_Call) Run(run func(tx *gorm.DB, category *entity.Category)) *MockCategory_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Category))
	})
	return _c
}

func (_c *MockCategory_Delete_Call) Return(_a0 error) *MockCategory_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategory_Delete_Call) RunAndReturn(run func(*gorm.DB, *entity.Category) error) *MockCategory_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: db, condition, orderBy
func (_m *MockCategory) List(db *gorm.DB, condition map[string]interface{}, orderBy string) ([]entity.Category, error) {
	ret := _m.Called(db, condition, orderBy)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) ([]entity.Category, error)); ok {
		return rf(db, condition, orderBy)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) []entity.Category); ok {
		r0 = rf(db, condition, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string) error); ok {
		r1 = rf(db, condition, orderBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategory_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategory_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - orderBy string
func (_e *MockCategory_Expecter) List(db interface{}, condition interface{}, orderBy interface{}) *MockCategory_List_Call {
	return &MockCategory_List_Call{Call: _e.mock.On("List", db, condition, orderBy)}
}

func (_c *MockCategory_List_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, orderBy string)) *MockCategory_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockCategory_List_Call) Return(_a0 []entity.Category, _a1 error) *MockCategory_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategory_List_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string) ([]entity.Category, error)) *MockCategory_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: db, condition, orderBy
func (_m *MockCategory) Search(db *gorm.DB, condition map[string]interface{}, orderBy string) (*entity.Category, error) {
	ret := _m.Called(db, condition, orderBy)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) (*entity.Category, error)); ok {
		return rf(db, condition, orderBy)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) *entity.Category); ok {
		r0 = rf(db, condition, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string) error); ok {
		r1 = rf(db, condition, orderBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategory_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCategory_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - orderBy string
func (_e *MockCategory_Expecter) Search(db interface{}, condition interface{}, orderBy interface{}) *MockCategory_Search_Call {
	return &MockCategory_Search_Call{Call: _e.mock.On("Search", db, condition, orderBy)}
}

func (_c *MockCategory_Search_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, orderBy string)) *MockCategory_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockCategory_Search_Call) Return(_a0 *entity.Category, _a1 error) *MockCategory_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategory_Search_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string) (*entity.Category, error)) *MockCategory_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, category
func (_m *MockCategory) Update(tx *gorm.DB, category *entity.Category) error {
	ret := _m.Called(tx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Category) error); ok {
		r0 = rf(tx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategory_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategory_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx *gorm.DB
//   - category *entity.Category
func (_e *MockCategory_Expecter) Update(tx interface{}, category interface{}) *MockCategory_Update_Call {
	return &MockCategory_Update_Call{Call: _e.mock.On("Update", tx, category)}
}

func (_c *MockCategory_Update_Call) Run(run func(tx *gorm.DB, category *entity.Category)) *MockCategory_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Category))
	})
	return _c
}

func (_c *MockCategory_Update_Call) Return(_a0 error) *MockCategory_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategory_Update_Call) RunAndReturn(run func(*gorm.DB, *entity.Category) error) *MockCategory_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategory creates a new instance of MockCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategory {
	mock := &MockCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
