// Code generated by mockery. DO NOT EDIT.

package repogeneric

import (
	entity "github.com/thanyakwaonueng/shopgo/lib/database/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockOrder is an autogenerated mock type for the Order type
type MockOrder struct {
	mock.Mock
}

type MockOrder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrder) EXPECT() *MockOrder_Expecter {
	return &MockOrder_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: db, condition
func (_m *MockOrder) Count(db *gorm.DB, condition map[string]interface{}) (int64, error) {
	ret := _m.Called(db, condition)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) (int64, error)); ok {
		return rf(db, condition)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) int64); ok {
		r0 = rf(db, condition)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}) error); ok {
		r1 = rf(db, condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrder_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockOrder_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
func (_e *MockOrder_Expecter) Count(db interface{}, condition interface{}) *MockOrder_Count_Call {
	return &MockOrder_Count_Call{Call: _e.mock.On("Count", db, condition)}
}

func (_c *MockOrder_Count_Call) Run(run func(db *gorm.DB, condition map[string]interface{})) *MockOrder_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *MockOrder_Count_Call) Return(_a0 int64, _a1 error) *MockOrder_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrder_Count_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}) (int64, error)) *MockOrder_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: tx, order
func (_m *MockOrder) Create(tx *gorm.DB, order *entity.Order) error {
	ret := _m.Called(tx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Order) error); ok {
		r0 = rf(tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrder_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrder_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx *gorm.DB
//   - order *entity.Order
func (_e *MockOrder_Expecter) Create(tx interface{}, order interface{}) *MockOrder_Create_Call {
	return &MockOrder_Create_Call{Call: _e.mock.On("Create", tx, order)}
}

func (_c *MockOrder_Create_Call) Run(run func(tx *gorm.DB, order *entity.Order)) *MockOrder_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Order))
	})
	return _c
}

func (_c *MockOrder_Create_Call) Return(_a0 error) *MockOrder_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrder_Create_Call) RunAndReturn(run func(*gorm.DB, *entity.Order) error) *MockOrder_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItem provides a mock function with given fields: tx, item
func (_m *MockOrder) CreateItem(tx *gorm.DB, item *entity.OrderItem) error {
	ret := _m.Called(tx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.OrderItem) error); ok {
		r0 = rf(tx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrder_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockOrder_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - tx *gorm.DB
//   - item *entity.OrderItem
func (_e *MockOrder_Expecter) CreateItem(tx interface{}, item interface{}) *MockOrder_CreateItem_Call {
	return &MockOrder_CreateItem_Call{Call: _e.mock.On("CreateItem", tx, item)}
}

func (_c *MockOrder_CreateItem_Call) Run(run func(tx *gorm.DB, item *entity.OrderItem)) *MockOrder_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.OrderItem))
	})
	return _c
}

func (_c *MockOrder_CreateItem_Call) Return(_a0 error) *MockOrder_CreateItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrder_CreateItem_Call) RunAndReturn(run func(*gorm.DB, *entity.OrderItem) error) *MockOrder_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithPagination provides a mock function with given fields: db, condition, orderBy, offset, limit
func (_m *MockOrder) ListWithPagination(db *gorm.DB, condition map[string]interface{}, orderBy string, offset int, limit int) ([]entity.Order, error) {
	ret := _m.Called(db, condition, orderBy, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPagination")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, int, int) ([]entity.Order, error)); ok {
		return rf(db, condition, orderBy, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, int, int) []entity.Order); ok {
		r0 = rf(db, condition, orderBy, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string, int, int) error); ok {
		r1 = rf(db, condition, orderBy, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrder_ListWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithPagination'
type MockOrder_ListWithPagination_Call struct {
	*mock.Call
}

// ListWithPagination is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - orderBy string
//   - offset int
//   - limit int
func (_e *MockOrder_Expecter) ListWithPagination(db interface{}, condition interface{}, orderBy interface{}, offset interface{}, limit interface{}) *MockOrder_ListWithPagination_Call {
	return &MockOrder_ListWithPagination_Call{Call: _e.mock.On("ListWithPagination", db, condition, orderBy, offset, limit)}
}

func (_c *MockOrder_ListWithPagination_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, orderBy string, offset int, limit int)) *MockOrder_ListWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockOrder_ListWithPagination_Call) Return(_a0 []entity.Order, _a1 error) *MockOrder_ListWithPagination_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrder_ListWithPagination_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string, int, int) ([]entity.Order, error)) *MockOrder_ListWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: db, condition, orderBy
func (_m *MockOrder) Search(db *gorm.DB, condition map[string]interface{}, orderBy string) (*entity.Order, error) {
	ret := _m.Called(db, condition, orderBy)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) (*entity.Order, error)); ok {
		return rf(db, condition, orderBy)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) *entity.Order); ok {
		r0 = rf(db, condition, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string) error); ok {
		r1 = rf(db, condition, orderBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrder_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockOrder_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - orderBy string
func (_e *MockOrder_Expecter) Search(db interface{}, condition interface{}, orderBy interface{}) *MockOrder_Search_Call {
	return &MockOrder_Search_Call{Call: _e.mock.On("Search", db, condition, orderBy)}
}

func (_c *MockOrder_Search_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, orderBy string)) *MockOrder_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockOrder_Search_Call) Return(_a0 *entity.Order, _a1 error) *MockOrder_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrder_Search_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string) (*entity.Order, error)) *MockOrder_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchWithItems provides a mock function with given fields: db, condition
func (_m *MockOrder) SearchWithItems(db *gorm.DB, condition map[string]interface{}) (*entity.Order, error) {
	ret := _m.Called(db, condition)

	if len(ret) == 0 {
		panic("no return value specified for SearchWithItems")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) (*entity.Order, error)); ok {
		return rf(db, condition)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) *entity.Order); ok {
		r0 = rf(db, condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}) error); ok {
		r1 = rf(db, condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrder_SearchWithItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchWithItems'
type MockOrder_SearchWithItems_Call struct {
	*mock.Call
}

// SearchWithItems is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
func (_e *MockOrder_Expecter) SearchWithItems(db interface{}, condition interface{}) *MockOrder_SearchWithItems_Call {
	return &MockOrder_SearchWithItems_Call{Call: _e.mock.On("SearchWithItems", db, condition)}
}

func (_c *MockOrder_SearchWithItems_Call) Run(run func(db *gorm.DB, condition map[string]interface{})) *MockOrder_SearchWithItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *MockOrder_SearchWithItems_Call) Return(_a0 *entity.Order, _a1 error) *MockOrder_SearchWithItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrder_SearchWithItems_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}) (*entity.Order, error)) *MockOrder_SearchWithItems_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, order
func (_m *MockOrder) Update(tx *gorm.DB, order *entity.Order) error {
	ret := _m.Called(tx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Order) error); ok {
		r0 = rf(tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrder_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrder_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx *gorm.DB
//   - order *entity.Order
func (_e *MockOrder_Expecter) Update(tx interface{}, order interface{}) *MockOrder_Update_Call {
	return &MockOrder_Update_Call{Call: _e.mock.On("Update", tx, order)}
}

func (_c *MockOrder_Update_Call) Run(run func(tx *gorm.DB, order *entity.Order)) *MockOrder_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Order))
	})
	return _c
}

func (_c *MockOrder_Update_Call) Return(_a0 error) *MockOrder_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrder_Update_Call) RunAndReturn(run func(*gorm.DB, *entity.Order) error) *MockOrder_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrder creates a new instance of MockOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrder {
	mock := &MockOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
