// Code generated by mockery. DO NOT EDIT.

package repogeneric

import (
	entity "github.com/thanyakwaonueng/shopgo/lib/database/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProduct is an autogenerated mock type for the Product type
type MockProduct struct {
	mock.Mock
}

type MockProduct_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProduct) EXPECT() *MockProduct_Expecter {
	return &MockProduct_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: db, condition, queryStr, queryArgs
func (_m *MockProduct) Count(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{}) (int64, error) {
	ret := _m.Called(db, condition, queryStr, queryArgs)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}) (int64, error)); ok {
		return rf(db, condition, queryStr, queryArgs)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}) int64); ok {
		r0 = rf(db, condition, queryStr, queryArgs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string, []interface{}) error); ok {
		r1 = rf(db, condition, queryStr, queryArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProduct_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockProduct_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - queryStr string
//   - queryArgs []interface{}
func (_e *MockProduct_Expecter) Count(db interface{}, condition interface{}, queryStr interface{}, queryArgs interface{}) *MockProduct_Count_Call {
	return &MockProduct_Count_Call{Call: _e.mock.On("Count", db, condition, queryStr, queryArgs)}
}

func (_c *MockProduct_Count_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{})) *MockProduct_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string), args[3].([]interface{}))
	})
	return _c
}

func (_c *MockProduct_Count_Call) Return(_a0 int64, _a1 error) *MockProduct_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProduct_Count_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string, []interface{}) (int64, error)) *MockProduct_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: db, product
func (_m *MockProduct) Create(db *gorm.DB, product *entity.Product) error {
	ret := _m.Called(db, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Product) error); ok {
		r0 = rf(db, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProduct_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - db *gorm.DB
//   - product *entity.Product
func (_e *MockProduct_Expecter) Create(db interface{}, product interface{}) *MockProduct_Create_Call {
	return &MockProduct_Create_Call{Call: _e.mock.On("Create", db, product)}
}

func (_c *MockProduct_Create_Call) Run(run func(db *gorm.DB, product *entity.Product)) *MockProduct_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Product))
	})
	return _c
}

func (_c *MockProduct_Create_Call) Return(_a0 error) *MockProduct_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_Create_Call) RunAndReturn(run func(*gorm.DB, *entity.Product) error) *MockProduct_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: tx, product
func (_m *MockProduct) Delete(tx *gorm.DB, product *entity.Product) error {
	ret := _m.Called(tx, product)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Product) error); ok {
		r0 = rf(tx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProduct_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - tx *gorm.DB
//   - product *entity.Product
func (_e *MockProduct_Expecter) Delete(tx interface{}, product interface{}) *MockProduct_Delete_Call {
	return &MockProduct_Delete_Call{Call: _e.mock.On("Delete", tx, product)}
}

func (_c *MockProduct_Delete_Call) Run(run func(tx *gorm.DB, product *entity.Product)) *MockProduct_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Product))
	})
	return _c
}

func (_c *MockProduct_Delete_Call) Return(_a0 error) *MockProduct_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_Delete_Call) RunAndReturn(run func(*gorm.DB, *entity.Product) error) *MockProduct_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithPagination provides a mock function with given fields: db, condition, queryStr, queryArgs, orderBy, offset, limit
func (_m *MockProduct) ListWithPagination(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{}, orderBy string, offset int, limit int) ([]entity.Product, error) {
	ret := _m.Called(db, condition, queryStr, queryArgs, orderBy, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPagination")
	}

	var r0 []entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) ([]entity.Product, error)); ok {
		return rf(db, condition, queryStr, queryArgs, orderBy, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) []entity.Product); ok {
		r0 = rf(db, condition, queryStr, queryArgs, orderBy, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) error); ok {
		r1 = rf(db, condition, queryStr, queryArgs, orderBy, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProduct_ListWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithPagination'
type MockProduct_ListWithPagination_Call struct {
	*mock.Call
}

// ListWithPagination is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - queryStr string
//   - queryArgs []interface{}
//   - orderBy string
//   - offset int
//   - limit int
func (_e *MockProduct_Expecter) ListWithPagination(db interface{}, condition interface{}, queryStr interface{}, queryArgs interface{}, orderBy interface{}, offset interface{}, limit interface{}) *MockProduct_ListWithPagination_Call {
	return &MockProduct_ListWithPagination_Call{Call: _e.mock.On("ListWithPagination", db, condition, queryStr, queryArgs, orderBy, offset, limit)}
}

func (_c *MockProduct_ListWithPagination_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{}, orderBy string, offset int, limit int)) *MockProduct_ListWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string), args[3].([]interface{}), args[4].(string), args[5].(int), args[6].(int))
	})
	return _c
}

func (_c *MockProduct_ListWithPagination_Call) Return(_a0 []entity.Product, _a1 error) *MockProduct_ListWithPagination_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProduct_ListWithPagination_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) ([]entity.Product, error)) *MockProduct_ListWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreStock provides a mock function with given fields: tx, productID, quantity
func (_m *MockProduct) RestoreStock(tx *gorm.DB, productID uuid.UUID, quantity int32) error {
	ret := _m.Called(tx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for RestoreStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID, int32) error); ok {
		r0 = rf(tx, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_RestoreStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreStock'
type MockProduct_RestoreStock_Call struct {
	*mock.Call
}

// RestoreStock is a helper method to define mock.On call
//   - tx *gorm.DB
//   - productID uuid.UUID
//   - quantity int32
func (_e *MockProduct_Expecter) RestoreStock(tx interface{}, productID interface{}, quantity interface{}) *MockProduct_RestoreStock_Call {
	return &MockProduct_RestoreStock_Call{Call: _e.mock.On("RestoreStock", tx, productID, quantity)}
}

func (_c *MockProduct_RestoreStock_Call) Run(run func(tx *gorm.DB, productID uuid.UUID, quantity int32)) *MockProduct_RestoreStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uuid.UUID), args[2].(int32))
	})
	return _c
}

func (_c *MockProduct_RestoreStock_Call) Return(_a0 error) *MockProduct_RestoreStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_RestoreStock_Call) RunAndReturn(run func(*gorm.DB, uuid.UUID, int32) error) *MockProduct_RestoreStock_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: db, condition
func (_m *MockProduct) Search(db *gorm.DB, condition map[string]interface{}) (*entity.Product, error) {
	ret := _m.Called(db, condition)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) (*entity.Product, error)); ok {
		return rf(db, condition)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) *entity.Product); ok {
		r0 = rf(db, condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}) error); ok {
		r1 = rf(db, condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProduct_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProduct_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
func (_e *MockProduct_Expecter) Search(db interface{}, condition interface{}) *MockProduct_Search_Call {
	return &MockProduct_Search_Call{Call: _e.mock.On("Search", db, condition)}
}

func (_c *MockProduct_Search_Call) Run(run func(db *gorm.DB, condition map[string]interface{})) *MockProduct_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *MockProduct_Search_Call) Return(_a0 *entity.Product, _a1 error) *MockProduct_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProduct_Search_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}) (*entity.Product, error)) *MockProduct_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchWithLock provides a mock function with given fields: tx, condition
func (_m *MockProduct) SearchWithLock(tx *gorm.DB, condition map[string]interface{}) (*entity.Product, error) {
	ret := _m.Called(tx, condition)

	if len(ret) == 0 {
		panic("no return value specified for SearchWithLock")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) (*entity.Product, error)); ok {
		return rf(tx, condition)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}) *entity.Product); ok {
		r0 = rf(tx, condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}) error); ok {
		r1 = rf(tx, condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProduct_SearchWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchWithLock'
type MockProduct_SearchWithLock_Call struct {
	*mock.Call
}

// SearchWithLock is a helper method to define mock.On call
//   - tx *gorm.DB
//   - condition map[string]interface{}
func (_e *MockProduct_Expecter) SearchWithLock(tx interface{}, condition interface{}) *MockProduct_SearchWithLock_Call {
	return &MockProduct_SearchWithLock_Call{Call: _e.mock.On("SearchWithLock", tx, condition)}
}

func (_c *MockProduct_SearchWithLock_Call) Run(run func(tx *gorm.DB, condition map[string]interface{})) *MockProduct_SearchWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *MockProduct_SearchWithLock_Call) Return(_a0 *entity.Product, _a1 error) *MockProduct_SearchWithLock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProduct_SearchWithLock_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}) (*entity.Product, error)) *MockProduct_SearchWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, product
func (_m *MockProduct) Update(tx *gorm.DB, product *entity.Product) error {
	ret := _m.Called(tx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.Product) error); ok {
		r0 = rf(tx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProduct_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx *gorm.DB
//   - product *entity.Product
func (_e *MockProduct_Expecter) Update(tx interface{}, product interface{}) *MockProduct_Update_Call {
	return &MockProduct_Update_Call{Call: _e.mock.On("Update", tx, product)}
}

func (_c *MockProduct_Update_Call) Run(run func(tx *gorm.DB, product *entity.Product)) *MockProduct_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.Product))
	})
	return _c
}

func (_c *MockProduct_Update_Call) Return(_a0 error) *MockProduct_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_Update_Call) RunAndReturn(run func(*gorm.DB, *entity.Product) error) *MockProduct_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProduct creates a new instance of MockProduct. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProduct(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProduct {
	mock := &MockProduct{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
