// Code generated by mockery. DO NOT EDIT.

package repogeneric

import (
	entity "github.com/thanyakwaonueng/shopgo/lib/database/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

type MockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUser) EXPECT() *MockUser_Expecter {
	return &MockUser_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: db, condition, queryStr, queryArgs
func (_m *MockUser) Count(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{}) (int64, error) {
	ret := _m.Called(db, condition, queryStr, queryArgs)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}) (int64, error)); ok {
		return rf(db, condition, queryStr, queryArgs)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}) int64); ok {
		r0 = rf(db, condition, queryStr, queryArgs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string, []interface{}) error); ok {
		r1 = rf(db, condition, queryStr, queryArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUser_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockUser_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - queryStr string
//   - queryArgs []interface{}
func (_e *MockUser_Expecter) Count(db interface{}, condition interface{}, queryStr interface{}, queryArgs interface{}) *MockUser_Count_Call {
	return &MockUser_Count_Call{Call: _e.mock.On("Count", db, condition, queryStr, queryArgs)}
}

func (_c *MockUser_Count_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{})) *MockUser_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string), args[3].([]interface{}))
	})
	return _c
}

func (_c *MockUser_Count_Call) Return(_a0 int64, _a1 error) *MockUser_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUser_Count_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string, []interface{}) (int64, error)) *MockUser_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: tx, user
func (_m *MockUser) Create(tx *gorm.DB, user *entity.User) error {
	ret := _m.Called(tx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.User) error); ok {
		r0 = rf(tx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUser_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUser_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tx *gorm.DB
//   - user *entity.User
func (_e *MockUser_Expecter) Create(tx interface{}, user interface{}) *MockUser_Create_Call {
	return &MockUser_Create_Call{Call: _e.mock.On("Create", tx, user)}
}

func (_c *MockUser_Create_Call) Run(run func(tx *gorm.DB, user *entity.User)) *MockUser_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.User))
	})
	return _c
}

func (_c *MockUser_Create_Call) Return(_a0 error) *MockUser_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUser_Create_Call) RunAndReturn(run func(*gorm.DB, *entity.User) error) *MockUser_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithPagination provides a mock function with given fields: db, condition, queryStr, queryArgs, orderBy, offset, limit
func (_m *MockUser) ListWithPagination(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{}, orderBy string, offset int, limit int) ([]entity.User, error) {
	ret := _m.Called(db, condition, queryStr, queryArgs, orderBy, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPagination")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) ([]entity.User, error)); ok {
		return rf(db, condition, queryStr, queryArgs, orderBy, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) []entity.User); ok {
		r0 = rf(db, condition, queryStr, queryArgs, orderBy, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) error); ok {
		r1 = rf(db, condition, queryStr, queryArgs, orderBy, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUser_ListWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithPagination'
type MockUser_ListWithPagination_Call struct {
	*mock.Call
}

// ListWithPagination is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - queryStr string
//   - queryArgs []interface{}
//   - orderBy string
//   - offset int
//   - limit int
func (_e *MockUser_Expecter) ListWithPagination(db interface{}, condition interface{}, queryStr interface{}, queryArgs interface{}, orderBy interface{}, offset interface{}, limit interface{}) *MockUser_ListWithPagination_Call {
	return &MockUser_ListWithPagination_Call{Call: _e.mock.On("ListWithPagination", db, condition, queryStr, queryArgs, orderBy, offset, limit)}
}

func (_c *MockUser_ListWithPagination_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, queryStr string, queryArgs []interface{}, orderBy string, offset int, limit int)) *MockUser_ListWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string), args[3].([]interface{}), args[4].(string), args[5].(int), args[6].(int))
	})
	return _c
}

func (_c *MockUser_ListWithPagination_Call) Return(_a0 []entity.User, _a1 error) *MockUser_ListWithPagination_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUser_ListWithPagination_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string, []interface{}, string, int, int) ([]entity.User, error)) *MockUser_ListWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: db, condition, orderBy
func (_m *MockUser) Search(db *gorm.DB, condition map[string]interface{}, orderBy string) (*entity.User, error) {
	ret := _m.Called(db, condition, orderBy)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) (*entity.User, error)); ok {
		return rf(db, condition, orderBy)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, string) *entity.User); ok {
		r0 = rf(db, condition, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, map[string]interface{}, string) error); ok {
		r1 = rf(db, condition, orderBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUser_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockUser_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - db *gorm.DB
//   - condition map[string]interface{}
//   - orderBy string
func (_e *MockUser_Expecter) Search(db interface{}, condition interface{}, orderBy interface{}) *MockUser_Search_Call {
	return &MockUser_Search_Call{Call: _e.mock.On("Search", db, condition, orderBy)}
}

func (_c *MockUser_Search_Call) Run(run func(db *gorm.DB, condition map[string]interface{}, orderBy string)) *MockUser_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(map[string]interface{}), args[2].(string))
	})
	return _c
}

func (_c *MockUser_Search_Call) Return(_a0 *entity.User, _a1 error) *MockUser_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUser_Search_Call) RunAndReturn(run func(*gorm.DB, map[string]interface{}, string) (*entity.User, error)) *MockUser_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: tx, user
func (_m *MockUser) Update(tx *gorm.DB, user *entity.User) error {
	ret := _m.Called(tx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.User) error); ok {
		r0 = rf(tx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUser_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUser_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx *gorm.DB
//   - user *entity.User
func (_e *MockUser_Expecter) Update(tx interface{}, user interface{}) *MockUser_Update_Call {
	return &MockUser_Update_Call{Call: _e.mock.On("Update", tx, user)}
}

func (_c *MockUser_Update_Call) Run(run func(tx *gorm.DB, user *entity.User)) *MockUser_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*entity.User))
	})
	return _c
}

func (_c *MockUser_Update_Call) Return(_a0 error) *MockUser_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUser_Update_Call) RunAndReturn(run func(*gorm.DB, *entity.User) error) *MockUser_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
